### ISSUE TITLE
Film selectioned but no play

### ISSUE THREAD

**Issue by nicolas2k** [phil65/plugin.video.amazon65#5]
Hi 

I can explorer some choice of film, I cannot play any film without error !

Why or how do I to investigate more ?

Thk

Nicolas

**Comment by nicolas2k** [comment]
pi@raspberrypi:~/.kodi/addons/plugin.video.amazon-test $ python default.py
Traceback (most recent call last):
  File "default.py", line 3, in <module>
    from resources.lib.startup import EntryPoint
  File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 6, in <module>
    from .network import *
  File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 6, in <module>
    import xbmcgui
ImportError: No module named xbmcgui
